#!/bin/bash

sbatch ./mixtext_jobs/sbatch/job1.sbatch
sbatch ./mixtext_jobs/sbatch/job2.sbatch
sbatch ./mixtext_jobs/sbatch/job3.sbatch
sbatch ./mixtext_jobs/sbatch/job4.sbatch
sbatch ./mixtext_jobs/sbatch/job5.sbatch
sbatch ./mixtext_jobs/sbatch/job6.sbatch
sbatch ./mixtext_jobs/sbatch/job7.sbatch
sbatch ./mixtext_jobs/sbatch/job8.sbatch
sbatch ./mixtext_jobs/sbatch/job9.sbatch
sbatch ./mixtext_jobs/sbatch/job10.sbatch
sbatch ./mixtext_jobs/sbatch/job11.sbatch
sbatch ./mixtext_jobs/sbatch/job12.sbatch
sbatch ./mixtext_jobs/sbatch/job13.sbatch
sbatch ./mixtext_jobs/sbatch/job14.sbatch
sbatch ./mixtext_jobs/sbatch/job15.sbatch
sbatch ./mixtext_jobs/sbatch/job16.sbatch
sbatch ./mixtext_jobs/sbatch/job17.sbatch
sbatch ./mixtext_jobs/sbatch/job18.sbatch
sbatch ./mixtext_jobs/sbatch/job19.sbatch
sbatch ./mixtext_jobs/sbatch/job20.sbatch
sbatch ./mixtext_jobs/sbatch/job21.sbatch
sbatch ./mixtext_jobs/sbatch/job22.sbatch
sbatch ./mixtext_jobs/sbatch/job23.sbatch
sbatch ./mixtext_jobs/sbatch/job24.sbatch
sbatch ./mixtext_jobs/sbatch/job25.sbatch
sbatch ./mixtext_jobs/sbatch/job26.sbatch
sbatch ./mixtext_jobs/sbatch/job27.sbatch
sbatch ./mixtext_jobs/sbatch/job28.sbatch
sbatch ./mixtext_jobs/sbatch/job29.sbatch
sbatch ./mixtext_jobs/sbatch/job30.sbatch
sbatch ./mixtext_jobs/sbatch/job31.sbatch
sbatch ./mixtext_jobs/sbatch/job32.sbatch
sbatch ./mixtext_jobs/sbatch/job33.sbatch
sbatch ./mixtext_jobs/sbatch/job34.sbatch
sbatch ./mixtext_jobs/sbatch/job35.sbatch
sbatch ./mixtext_jobs/sbatch/job36.sbatch
sbatch ./mixtext_jobs/sbatch/job37.sbatch
sbatch ./mixtext_jobs/sbatch/job38.sbatch
sbatch ./mixtext_jobs/sbatch/job39.sbatch
sbatch ./mixtext_jobs/sbatch/job40.sbatch
sbatch ./mixtext_jobs/sbatch/job41.sbatch
sbatch ./mixtext_jobs/sbatch/job42.sbatch
sbatch ./mixtext_jobs/sbatch/job43.sbatch
sbatch ./mixtext_jobs/sbatch/job44.sbatch
sbatch ./mixtext_jobs/sbatch/job45.sbatch
sbatch ./mixtext_jobs/sbatch/job46.sbatch
sbatch ./mixtext_jobs/sbatch/job47.sbatch
sbatch ./mixtext_jobs/sbatch/job48.sbatch
sbatch ./mixtext_jobs/sbatch/job49.sbatch
sbatch ./mixtext_jobs/sbatch/job50.sbatch
sbatch ./mixtext_jobs/sbatch/job51.sbatch
sbatch ./mixtext_jobs/sbatch/job52.sbatch
sbatch ./mixtext_jobs/sbatch/job53.sbatch
sbatch ./mixtext_jobs/sbatch/job54.sbatch
sbatch ./mixtext_jobs/sbatch/job55.sbatch
sbatch ./mixtext_jobs/sbatch/job56.sbatch
sbatch ./mixtext_jobs/sbatch/job57.sbatch
sbatch ./mixtext_jobs/sbatch/job58.sbatch
sbatch ./mixtext_jobs/sbatch/job59.sbatch
sbatch ./mixtext_jobs/sbatch/job60.sbatch
sbatch ./mixtext_jobs/sbatch/job61.sbatch
sbatch ./mixtext_jobs/sbatch/job62.sbatch
sbatch ./mixtext_jobs/sbatch/job63.sbatch
sbatch ./mixtext_jobs/sbatch/job64.sbatch
sbatch ./mixtext_jobs/sbatch/job65.sbatch
sbatch ./mixtext_jobs/sbatch/job66.sbatch
sbatch ./mixtext_jobs/sbatch/job67.sbatch
sbatch ./mixtext_jobs/sbatch/job68.sbatch
sbatch ./mixtext_jobs/sbatch/job69.sbatch
sbatch ./mixtext_jobs/sbatch/job70.sbatch
sbatch ./mixtext_jobs/sbatch/job71.sbatch
sbatch ./mixtext_jobs/sbatch/job72.sbatch
sbatch ./mixtext_jobs/sbatch/job73.sbatch
sbatch ./mixtext_jobs/sbatch/job74.sbatch
sbatch ./mixtext_jobs/sbatch/job75.sbatch
sbatch ./mixtext_jobs/sbatch/job76.sbatch
sbatch ./mixtext_jobs/sbatch/job77.sbatch
sbatch ./mixtext_jobs/sbatch/job78.sbatch
sbatch ./mixtext_jobs/sbatch/job79.sbatch
sbatch ./mixtext_jobs/sbatch/job80.sbatch
sbatch ./mixtext_jobs/sbatch/job81.sbatch
sbatch ./mixtext_jobs/sbatch/job82.sbatch
sbatch ./mixtext_jobs/sbatch/job83.sbatch
sbatch ./mixtext_jobs/sbatch/job84.sbatch
sbatch ./mixtext_jobs/sbatch/job85.sbatch
sbatch ./mixtext_jobs/sbatch/job86.sbatch
sbatch ./mixtext_jobs/sbatch/job87.sbatch
sbatch ./mixtext_jobs/sbatch/job88.sbatch
sbatch ./mixtext_jobs/sbatch/job89.sbatch
sbatch ./mixtext_jobs/sbatch/job90.sbatch
sbatch ./mixtext_jobs/sbatch/job91.sbatch
sbatch ./mixtext_jobs/sbatch/job92.sbatch
sbatch ./mixtext_jobs/sbatch/job93.sbatch
sbatch ./mixtext_jobs/sbatch/job94.sbatch
sbatch ./mixtext_jobs/sbatch/job95.sbatch
sbatch ./mixtext_jobs/sbatch/job96.sbatch
sbatch ./mixtext_jobs/sbatch/job97.sbatch
sbatch ./mixtext_jobs/sbatch/job98.sbatch
sbatch ./mixtext_jobs/sbatch/job99.sbatch
sbatch ./mixtext_jobs/sbatch/job100.sbatch
